### ISSUE TITLE
BETA APP CRASHES DURING LAUNCH

### ISSUE THREAD

**Issue by Moutony** [tommasoberlose/another-widget#62]
Beta app crashes EVERYTIME I launch it, I had to uninstall it... 
It seems it is because i'm a Beta user: even after reinstalling the beta version, the app keeps crashing...
The app works when I quit the Beta and reinstall the public version.

My phone: Android 9 with MIUI 11 (Xiaomi).

**Comment by Moutony** [comment]
java.lang.OutOfMemoryError
	at android.graphics.Bitmap.nativeCreate(Native Method)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:1046)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:1000)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:950)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:911)
	at com.tommasoberlose.anotherwidget.helpers.BitmapHelper.getBitmapFromView(BitmapHelper.kt:24)
	at com.tommasoberlose.anotherwidget.helpers.BitmapHelper.getBitmapFromView$default(BitmapHelper.kt:16)
	at com.tommasoberlose.anotherwidget.ui.widgets.MainWidget$Companion.generateWidgetView(MainWidget.kt:107)
	at com.tommasoberlose.anotherwidget.ui.widgets.MainWidget$Companion.updateAppWidget$app_release(MainWidget.kt:100)
	at com.tommasoberlose.anotherwidget.ui.widgets.MainWidget.onUpdate(MainWidget.kt:49)
	at android.appwidget.AppWidgetProvider.onReceive(AppWidgetProvider.java:66)
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3412)
	at android.app.ActivityThread.access$1300(ActivityThread.java:200)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1684)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:201)
	at android.app.ActivityThread.main(ActivityThread.java:6810)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

**Comment by leoyinjou** [comment]
Getting this now just after the most recent update (beta i believe) v2.0.5. OnePlus 7 Pro Android 10 OxygenOS 10.0.5.

**Comment by tjsuominen** [comment]
Happens on 2.0.4 as well, the widged does not appear UNTILL added to the homescreen manually. OP5 with Android 9. Also the ADD button in app wasn't visible at least on first launch...

**Comment by tommasoberlose** [comment]
A new beta version of the app will be published asap.

**Comment by tommasoberlose** [comment]
> Happens on 2.0.4 as well, the widged does not appear UNTILL added to the homescreen manually. OP5 with Android 9. Also the ADD button in app wasn't visible at least on first launch...

The "ADD" button is shown only when you add the widget from the launcher.

**Comment by leoyinjou** [comment]
> A new beta version of the app will be published asap.

The latest version updated on Play Store fixed the crash, and also allowed calendar events to update in a minute after calendar/event update on my OnePlus 7 Pro running Android 10 without need to manually refresh, and no need to disable battery optimisation at all. Seems fixed, great job!

**Comment by Moutony** [comment]
> > A new beta version of the app will be published asap.
> 
> The latest version updated on Play Store fixed the crash, and also allowed calendar events to update in a minute after calendar/event update on my OnePlus 7 Pro running Android 10 without need to manually refresh, and no need to disable battery optimisation at all. Seems fixed, great job!

The new beta stills crash for me: java.lang.OutOfMemoryError...

**Comment by tommasoberlose** [comment]
> > > A new beta version of the app will be published asap.
> > 
> > 
> > The latest version updated on Play Store fixed the crash, and also allowed calendar events to update in a minute after calendar/event update on my OnePlus 7 Pro running Android 10 without need to manually refresh, and no need to disable battery optimisation at all. Seems fixed, great job!
> 
> The new beta stills crash for me: java.lang.OutOfMemoryError...

I'm working on this problem. I can't figure out why on some devices the widget can't generate the view and throw the OutOfMemory exception.
I've just added a few log events in the latest beta version (code 74) and from now on you can check for any updates on #78.
